export const categories = [
  {
    id: "education",
    name: "Education",
    icon: "GraduationCap",
    description: "Schools, enrollment, and educational facilities data",
    datasets: 24,
    color: "emerald",
  },
  {
    id: "population",
    name: "Population & Demographics",
    icon: "Users",
    description: "Census, age distribution, and socioeconomic indicators",
    datasets: 18,
    color: "teal",
  },
  {
    id: "health",
    name: "Health & Hospitals",
    icon: "Heart",
    description: "Healthcare facilities, health workers, and health statistics",
    datasets: 15,
    color: "green",
  },
  {
    id: "infrastructure",
    name: "Infrastructure",
    icon: "Building2",
    description: "Roads, bridges, public buildings, and utilities",
    datasets: 32,
    color: "lime",
  },
  {
    id: "agriculture",
    name: "Agriculture & Fisheries",
    icon: "Wheat",
    description: "Farmland, crop production, and agricultural data",
    datasets: 21,
    color: "emerald",
  },
  {
    id: "environment",
    name: "Environment",
    icon: "TreePine",
    description: "Forest cover, watersheds, and environmental monitoring",
    datasets: 14,
    color: "green",
  },
  {
    id: "economy",
    name: "Business & Economy",
    icon: "TrendingUp",
    description: "Business registration, investment, and economic indicators",
    datasets: 19,
    color: "teal",
  },
  {
    id: "governance",
    name: "Governance & Budget",
    icon: "Landmark",
    description: "Budget, expenditures, bids, and procurement data",
    datasets: 27,
    color: "emerald",
  },
  {
    id: "safety",
    name: "Public Safety",
    icon: "Shield",
    description: "Police, fire stations, and emergency response data",
    datasets: 11,
    color: "green",
  },
  {
    id: "disaster",
    name: "Disaster Risk Reduction",
    icon: "AlertTriangle",
    description: "Hazard maps, evacuation centers, and disaster data",
    datasets: 16,
    color: "lime",
  },
  {
    id: "social",
    name: "Social Services",
    icon: "HeartHandshake",
    description: "4Ps beneficiaries, PWD, senior citizens data",
    datasets: 13,
    color: "teal",
  },
  {
    id: "tourism",
    name: "Tourism & Culture",
    icon: "Map",
    description: "Tourist sites, heritage, and cultural events",
    datasets: 9,
    color: "emerald",
  },
  {
    id: "employment",
    name: "Employment & Labor",
    icon: "Briefcase",
    description: "Job vacancies, skills demand, and labor statistics",
    datasets: 12,
    color: "green",
  },
  {
    id: "ict",
    name: "ICT & Digital",
    icon: "Wifi",
    description: "Internet coverage, WiFi sites, and digital services",
    datasets: 8,
    color: "teal",
  },
  {
    id: "utilities",
    name: "Public Utilities",
    icon: "Droplets",
    description: "Water, electricity, and sanitation coverage",
    datasets: 10,
    color: "lime",
  },
  {
    id: "finance",
    name: "Finance & Revenue",
    icon: "Banknote",
    description: "Tax collection, revenue sources, and fiscal data",
    datasets: 15,
    color: "emerald",
  },
  {
    id: "land",
    name: "Land & Housing",
    icon: "Home",
    description: "Land use, zoning, and housing projects",
    datasets: 11,
    color: "green",
  },
  {
    id: "transparency",
    name: "Open Government",
    icon: "Eye",
    description: "FOI requests, announcements, and metadata",
    datasets: 6,
    color: "teal",
  },
  {
    id: "climate",
    name: "Climate & Weather",
    icon: "Cloud",
    description: "Rainfall, temperature, and climate monitoring",
    datasets: 8,
    color: "lime",
  },
  {
    id: "youth",
    name: "Youth & Education Research",
    icon: "BookOpen",
    description: "School performance, enrollment trends, and research",
    datasets: 7,
    color: "emerald",
  },
  {
    id: "gis",
    name: "GIS / Mapping",
    icon: "MapPin",
    description: "Boundaries, road networks, and geographic data",
    datasets: 22,
    color: "green",
  },
  {
    id: "api",
    name: "Developer APIs",
    icon: "Code",
    description: "REST APIs, GeoJSON endpoints, and bulk downloads",
    datasets: 5,
    color: "teal",
  },
  {
    id: "disaster-risk",
    name: "Disaster Risk",
    icon: "AlertTriangle",
    description: "Flood susceptibility data, historical flood events, and drainage systems",
    datasets: 1,
    color: "lime",
  },
]

export const recentDatasets = [
  {
    id: "1",
    title: "Public Elementary Schools Directory 2024",
    description:
      "Complete listing of all public elementary schools in Tarlac Province with enrollment data, teacher count, and facilities information.",
    publisher: "DepEd Tarlac",
    category: "Education",
    resources: 3,
    size: "2.4 MB",
    publishedDate: "Dec 1, 2025",
    downloads: 1247,
  },
  {
    id: "2",
    title: "Provincial Road Network GeoJSON",
    description:
      "Geographic data of all provincial roads including road condition assessments and maintenance schedules.",
    publisher: "DPWH Tarlac",
    category: "Infrastructure",
    resources: 5,
    size: "45.8 MB",
    publishedDate: "Nov 28, 2025",
    downloads: 892,
  },
  {
    id: "3",
    title: "Municipal Population Census 2024",
    description: "Population statistics per municipality and barangay including age groups and gender distribution.",
    publisher: "PSA Region III",
    category: "Population",
    resources: 2,
    size: "1.1 MB",
    publishedDate: "Nov 25, 2025",
    downloads: 2103,
  },
  {
    id: "4",
    title: "Rural Health Units Directory",
    description:
      "Complete listing of RHUs and barangay health stations with personnel, services, and contact information.",
    publisher: "DOH Tarlac",
    category: "Health",
    resources: 4,
    size: "890 KB",
    publishedDate: "Nov 22, 2025",
    downloads: 654,
  },
  {
    id: "5",
    title: "Rice Production Statistics 2024",
    description:
      "Detailed crop production data for rice including area harvested, yield, and farmgate prices by municipality.",
    publisher: "DA Region III",
    category: "Agriculture",
    resources: 6,
    size: "3.2 MB",
    publishedDate: "Nov 18, 2025",
    downloads: 1567,
  },
  {
    id: "6",
    title: "2025 Annual Investment Program",
    description:
      "Provincial government infrastructure projects with budget allocation, timeline, and implementation status.",
    publisher: "PGO Tarlac",
    category: "Governance",
    resources: 8,
    size: "12.4 MB",
    publishedDate: "Nov 15, 2025",
    downloads: 934,
  },
]

export const allDatasets = [
  {
    id: "1",
    title: "Public Elementary Schools Directory 2024",
    description:
      "Complete listing of all public elementary schools in Tarlac Province with enrollment data, teacher count, and facilities information. Includes geolocation data for mapping.",
    publisher: "DepEd Tarlac",
    category: "Education",
    resources: [
      { name: "Schools List (CSV)", format: "CSV", size: "1.2 MB" },
      { name: "Schools GeoJSON", format: "GeoJSON", size: "800 KB" },
      { name: "Data Dictionary", format: "PDF", size: "400 KB" },
    ],
    size: "2.4 MB",
    publishedDate: "Dec 1, 2025",
    updatedDate: "Dec 1, 2025",
    downloads: 1247,
    license: "Open Data Commons",
    tags: ["schools", "education", "elementary", "enrollment", "teachers"],
  },
  {
    id: "2",
    title: "Provincial Road Network GeoJSON",
    description:
      "Geographic data of all provincial roads including road condition assessments and maintenance schedules. Contains detailed polyline data with road classification and surface type attributes.",
    publisher: "DPWH Tarlac",
    category: "Infrastructure",
    resources: [
      { name: "Road Network (GeoJSON)", format: "GeoJSON", size: "35 MB" },
      { name: "Road Conditions (CSV)", format: "CSV", size: "2.8 MB" },
      { name: "Maintenance Schedule (XLSX)", format: "XLSX", size: "1.5 MB" },
      { name: "Road Classification Guide", format: "PDF", size: "3.5 MB" },
      { name: "API Endpoint Documentation", format: "PDF", size: "3 MB" },
    ],
    size: "45.8 MB",
    publishedDate: "Nov 28, 2025",
    updatedDate: "Nov 28, 2025",
    downloads: 892,
    license: "Open Data Commons",
    tags: ["roads", "infrastructure", "transportation", "gis", "maintenance"],
  },
  {
    id: "3",
    title: "Municipal Population Census 2024",
    description:
      "Population statistics per municipality and barangay including age groups and gender distribution. Based on the 2024 census conducted by the Philippine Statistics Authority.",
    publisher: "PSA Region III",
    category: "Population",
    resources: [
      { name: "Population by Municipality (CSV)", format: "CSV", size: "650 KB" },
      { name: "Age Distribution (XLSX)", format: "XLSX", size: "450 KB" },
    ],
    size: "1.1 MB",
    publishedDate: "Nov 25, 2025",
    updatedDate: "Nov 25, 2025",
    downloads: 2103,
    license: "Open Data Commons",
    tags: ["population", "census", "demographics", "age", "gender"],
  },
  {
    id: "4",
    title: "Rural Health Units Directory",
    description:
      "Complete listing of RHUs and barangay health stations with personnel, services, and contact information. Includes vaccination center designations and operating hours.",
    publisher: "DOH Tarlac",
    category: "Health",
    resources: [
      { name: "RHU Directory (CSV)", format: "CSV", size: "320 KB" },
      { name: "Health Stations (GeoJSON)", format: "GeoJSON", size: "280 KB" },
      { name: "Services Offered (XLSX)", format: "XLSX", size: "190 KB" },
      { name: "Personnel Count", format: "CSV", size: "100 KB" },
    ],
    size: "890 KB",
    publishedDate: "Nov 22, 2025",
    updatedDate: "Nov 22, 2025",
    downloads: 654,
    license: "Open Data Commons",
    tags: ["health", "rhu", "hospitals", "healthcare", "vaccination"],
  },
  {
    id: "5",
    title: "Rice Production Statistics 2024",
    description:
      "Detailed crop production data for rice including area harvested, yield, and farmgate prices by municipality. Covers both wet and dry seasons with irrigation coverage data.",
    publisher: "DA Region III",
    category: "Agriculture",
    resources: [
      { name: "Production Data (CSV)", format: "CSV", size: "1.8 MB" },
      { name: "Yield Statistics (XLSX)", format: "XLSX", size: "650 KB" },
      { name: "Farmgate Prices (CSV)", format: "CSV", size: "420 KB" },
      { name: "Irrigation Coverage (GeoJSON)", format: "GeoJSON", size: "250 KB" },
      { name: "Seasonal Comparison", format: "PDF", size: "50 KB" },
      { name: "Methodology Notes", format: "PDF", size: "30 KB" },
    ],
    size: "3.2 MB",
    publishedDate: "Nov 18, 2025",
    updatedDate: "Nov 18, 2025",
    downloads: 1567,
    license: "Open Data Commons",
    tags: ["agriculture", "rice", "crops", "farming", "production"],
  },
  {
    id: "6",
    title: "2025 Annual Investment Program",
    description:
      "Provincial government infrastructure projects with budget allocation, timeline, and implementation status. Includes procurement schedules and contractor information.",
    publisher: "PGO Tarlac",
    category: "Governance",
    resources: [
      { name: "Project List (XLSX)", format: "XLSX", size: "4.2 MB" },
      { name: "Budget Allocation (CSV)", format: "CSV", size: "1.8 MB" },
      { name: "Timeline Gantt (PDF)", format: "PDF", size: "2.4 MB" },
      { name: "Procurement Schedule", format: "XLSX", size: "1.2 MB" },
      { name: "Implementation Status", format: "CSV", size: "850 KB" },
      { name: "Project Locations (GeoJSON)", format: "GeoJSON", size: "1.2 MB" },
      { name: "Summary Report", format: "PDF", size: "600 KB" },
      { name: "Methodology", format: "PDF", size: "140 KB" },
    ],
    size: "12.4 MB",
    publishedDate: "Nov 15, 2025",
    updatedDate: "Nov 15, 2025",
    downloads: 934,
    license: "Open Data Commons",
    tags: ["budget", "infrastructure", "projects", "procurement", "government"],
  },
  {
    id: "7",
    title: "Flood Hazard Map Data",
    description:
      "Comprehensive flood susceptibility data including historical flood events, drainage systems, and vulnerable areas. GIS-ready format for integration with other datasets.",
    publisher: "PDRRMO Tarlac",
    category: "Disaster Risk",
    resources: [
      { name: "Flood Zones (GeoJSON)", format: "GeoJSON", size: "8.5 MB" },
      { name: "Historical Events (CSV)", format: "CSV", size: "420 KB" },
      { name: "Drainage Systems", format: "GeoJSON", size: "2.1 MB" },
    ],
    size: "11 MB",
    publishedDate: "Nov 10, 2025",
    updatedDate: "Nov 10, 2025",
    downloads: 756,
    license: "Open Data Commons",
    tags: ["flood", "disaster", "hazard", "gis", "emergency"],
  },
  {
    id: "8",
    title: "Registered Businesses Directory 2024",
    description:
      "Complete listing of DTI and SEC registered businesses in Tarlac Province by industry classification, municipality, and capitalization range.",
    publisher: "DTI Tarlac",
    category: "Economy",
    resources: [
      { name: "Business Registry (CSV)", format: "CSV", size: "5.2 MB" },
      { name: "Industry Classification", format: "XLSX", size: "1.8 MB" },
    ],
    size: "7 MB",
    publishedDate: "Nov 5, 2025",
    updatedDate: "Nov 5, 2025",
    downloads: 1123,
    license: "Open Data Commons",
    tags: ["business", "economy", "registration", "industry", "commerce"],
  },
  {
    id: "9",
    title: "Barangay Boundaries GeoJSON",
    description:
      "Official administrative boundaries of all barangays in Tarlac Province. Includes population density overlay and land area computations.",
    publisher: "NAMRIA",
    category: "GIS",
    resources: [
      { name: "Barangay Boundaries (GeoJSON)", format: "GeoJSON", size: "12 MB" },
      { name: "Municipality Boundaries", format: "GeoJSON", size: "3.2 MB" },
      { name: "Land Area Data", format: "CSV", size: "180 KB" },
    ],
    size: "15.4 MB",
    publishedDate: "Oct 28, 2025",
    updatedDate: "Oct 28, 2025",
    downloads: 2341,
    license: "Open Data Commons",
    tags: ["boundaries", "barangay", "gis", "administrative", "namria"],
  },
  {
    id: "10",
    title: "Public High Schools Directory 2024",
    description:
      "Directory of all public high schools including senior high school track offerings, enrollment data, and teacher qualifications.",
    publisher: "DepEd Tarlac",
    category: "Education",
    resources: [
      { name: "High Schools List (CSV)", format: "CSV", size: "980 KB" },
      { name: "SHS Tracks (XLSX)", format: "XLSX", size: "450 KB" },
      { name: "School Locations (GeoJSON)", format: "GeoJSON", size: "320 KB" },
    ],
    size: "1.75 MB",
    publishedDate: "Oct 20, 2025",
    updatedDate: "Oct 20, 2025",
    downloads: 876,
    license: "Open Data Commons",
    tags: ["schools", "education", "high school", "senior high", "enrollment"],
  },
  {
    id: "11",
    title: "Tourist Sites and Attractions",
    description:
      "Accredited tourist destinations, heritage sites, and cultural landmarks with visitor statistics and accommodation directory.",
    publisher: "DOT Region III",
    category: "Tourism",
    resources: [
      { name: "Tourist Sites (CSV)", format: "CSV", size: "380 KB" },
      { name: "Visitor Statistics (XLSX)", format: "XLSX", size: "220 KB" },
      { name: "Site Locations (GeoJSON)", format: "GeoJSON", size: "150 KB" },
    ],
    size: "750 KB",
    publishedDate: "Oct 15, 2025",
    updatedDate: "Oct 15, 2025",
    downloads: 543,
    license: "Open Data Commons",
    tags: ["tourism", "heritage", "culture", "attractions", "visitors"],
  },
  {
    id: "12",
    title: "Water Service Coverage Data",
    description:
      "Water district service area coverage including household connections, water quality monitoring results, and expansion plans.",
    publisher: "Tarlac Water District",
    category: "Utilities",
    resources: [
      { name: "Service Coverage (GeoJSON)", format: "GeoJSON", size: "4.2 MB" },
      { name: "Connections Data (CSV)", format: "CSV", size: "1.1 MB" },
      { name: "Water Quality Results", format: "XLSX", size: "680 KB" },
    ],
    size: "6 MB",
    publishedDate: "Oct 10, 2025",
    updatedDate: "Oct 10, 2025",
    downloads: 421,
    license: "Open Data Commons",
    tags: ["water", "utilities", "coverage", "quality", "service"],
  },
]

export const statistics = {
  datasets: 287,
  resources: 1842,
  publishers: 24,
  totalSize: "12.6 GB",
}

export const featuredMaps = [
  {
    id: "flood-hazard",
    title: "Flood Hazard Map",
    description: "Areas susceptible to flooding based on historical data",
    thumbnail: "/flood-hazard-map-green.jpg",
  },
  {
    id: "schools",
    title: "Schools Location Map",
    description: "All public and private schools across the province",
    thumbnail: "/school-locations-map-green.jpg",
  },
  {
    id: "health-facilities",
    title: "Health Facilities Map",
    description: "Hospitals, RHUs, and health stations",
    thumbnail: "/hospital-locations-map-green.jpg",
  },
]
