export const mapLayers = [
  {
    id: "flood-hazard",
    name: "Flood Hazard Map",
    description: "Areas susceptible to flooding based on historical data and terrain analysis",
    category: "Disaster Risk",
    thumbnail: "/flood-hazard-map-green.jpg",
    datasets: ["flood-zones", "drainage-systems", "historical-events"],
    lastUpdated: "Nov 2025",
  },
  {
    id: "schools",
    name: "Schools Location Map",
    description: "All public and private schools across the province with enrollment data",
    category: "Education",
    thumbnail: "/school-locations-map-green.jpg",
    datasets: ["elementary-schools", "high-schools", "colleges"],
    lastUpdated: "Dec 2025",
  },
  {
    id: "health-facilities",
    name: "Health Facilities Map",
    description: "Hospitals, RHUs, barangay health stations, and vaccination centers",
    category: "Health",
    thumbnail: "/hospital-locations-map-green.jpg",
    datasets: ["hospitals", "rhu", "health-stations"],
    lastUpdated: "Nov 2025",
  },
  {
    id: "road-network",
    name: "Road Network Map",
    description: "Provincial, municipal, and national roads with condition assessments",
    category: "Infrastructure",
    thumbnail: "/road-network-map-green-theme-tarlac.jpg",
    datasets: ["provincial-roads", "municipal-roads", "national-highways"],
    lastUpdated: "Nov 2025",
  },
  {
    id: "barangay-boundaries",
    name: "Administrative Boundaries",
    description: "Official boundaries of municipalities and barangays",
    category: "GIS",
    thumbnail: "/administrative-boundaries-map-tarlac-green.jpg",
    datasets: ["barangay-boundaries", "municipality-boundaries"],
    lastUpdated: "Oct 2025",
  },
  {
    id: "land-use",
    name: "Land Use Classification",
    description: "Agricultural, residential, commercial, and protected areas",
    category: "Environment",
    thumbnail: "/land-use-map-classification-green-theme.jpg",
    datasets: ["land-classification", "zoning-data"],
    lastUpdated: "Sep 2025",
  },
  {
    id: "evacuation-centers",
    name: "Evacuation Centers",
    description: "Community evacuation centers and emergency shelters",
    category: "Disaster Risk",
    thumbnail: "/evacuation-centers-map-markers-green.jpg",
    datasets: ["evacuation-centers", "capacity-data"],
    lastUpdated: "Nov 2025",
  },
  {
    id: "agricultural-lands",
    name: "Agricultural Areas",
    description: "Farmland distribution, crop types, and irrigation coverage",
    category: "Agriculture",
    thumbnail: "/agricultural-farmland-map-rice-fields-green.jpg",
    datasets: ["farmland-data", "irrigation-systems"],
    lastUpdated: "Nov 2025",
  },
  {
    id: "population-density",
    name: "Population Density",
    description: "Heat map showing population distribution across the province",
    category: "Demographics",
    thumbnail: "/population-density-heat-map-green-theme.jpg",
    datasets: ["population-census", "household-data"],
    lastUpdated: "Nov 2025",
  },
]

export const gisDatasets = [
  {
    id: "barangay-boundaries-geojson",
    name: "Barangay Boundaries",
    format: "GeoJSON",
    size: "12 MB",
    description: "Official administrative boundaries of all barangays",
  },
  {
    id: "municipality-boundaries-geojson",
    name: "Municipality Boundaries",
    format: "GeoJSON",
    size: "3.2 MB",
    description: "Municipal boundaries with land area data",
  },
  {
    id: "road-network-geojson",
    name: "Road Network",
    format: "GeoJSON",
    size: "35 MB",
    description: "Complete road network with classification",
  },
  {
    id: "rivers-geojson",
    name: "Rivers & Water Bodies",
    format: "GeoJSON",
    size: "8.5 MB",
    description: "Major rivers, creeks, and water bodies",
  },
  {
    id: "schools-geojson",
    name: "School Locations",
    format: "GeoJSON",
    size: "1.2 MB",
    description: "Point data for all schools",
  },
  {
    id: "health-facilities-geojson",
    name: "Health Facilities",
    format: "GeoJSON",
    size: "800 KB",
    description: "Point data for health facilities",
  },
]
